<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-T29RGA0" failures="0" tests="5" name="com.ds.testLayer.BuyFunctionalityTest" time="0.045" errors="1" timestamp="2023-02-09T15:40:58 IST" skipped="4">
  <testcase classname="com.ds.testLayer.BuyFunctionalityTest" name="VerifyBuyFunctionalitywithIntrdayCustomt" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyBuyFunctionalitywithIntrdayCustomt -->
  <system-out/>
  <testcase classname="com.ds.testLayer.BuyFunctionalityTest" name="start" time="0.045">
    <error message="Cannot invoke &quot;org.apache.log4j.Logger.info(Object)&quot; because &quot;com.ds.testBase.TestBase.logger&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.log4j.Logger.info(Object)" because "com.ds.testBase.TestBase.logger" is null
at com.ds.testBase.TestBase.start(TestBase.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- start -->
  <system-out/>
  <testcase classname="com.ds.testLayer.BuyFunctionalityTest" name="VerifyBuyFunctionality" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyBuyFunctionality -->
  <system-out/>
  <testcase classname="com.ds.testLayer.BuyFunctionalityTest" name="VerifyBuyFunctionalitywithlongtermcustomlimit" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyBuyFunctionalitywithlongtermcustomlimit -->
  <system-out/>
  <testcase classname="com.ds.testLayer.BuyFunctionalityTest" name="VerifyBuyFunctionalitywithIntrdayMarket" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyBuyFunctionalitywithIntrdayMarket -->
  <system-out/>
</testsuite> <!-- com.ds.testLayer.BuyFunctionalityTest -->
