<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-T29RGA0" failures="0" tests="1" name="Default test" time="0.145" errors="0" timestamp="2023-02-15T14:42:24 IST">
  <testcase classname="com.ds.testBase.TestBase" name="@BeforeTest start" time="0.054">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;org.apache.log4j.Logger.info(Object)&amp;quot; because &amp;quot;com.ds.testBase.TestBase.logger&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.log4j.Logger.info(Object)" because "com.ds.testBase.TestBase.logger" is null
at com.ds.testBase.TestBase.start(TestBase.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:637)
at org.testng.TestRunner.beforeRun(TestRunner.java:627)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest start -->
  <testcase classname="com.ds.testBase.TestBase" name="@BeforeMethod setUp" time="-1.67645234468E9">
    <skipped/>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase classname="com.ds.testBase.TestBase" name="@AfterMethod tearDown" time="-1.676452344694E9">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase classname="com.ds.testBase.TestBase" name="@AfterTest end" time="-1.676452344701E9">
    <skipped/>
  </testcase> <!-- @AfterTest end -->
  <testcase classname="com.ds.testLayer.LoginPageTest" name="verifyLoginWithCorrectCred" time="0.0">
    <skipped/>
  </testcase> <!-- verifyLoginWithCorrectCred -->
</testsuite> <!-- Default test -->
